apiVersion: v1
kind: Service
metadata:
  name: mitra-panel-topup
  namespace: default
spec:
  selector:
    app: mitra-panel-topup
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

